services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: compose-db-91bb2f2e73404fe2
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  runner:
    image: training/automation-runner:1.0
    privileged: true
    environment:
      AUTH_REQUIRED: "false"
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host

volumes:
  db-data:
